cpmaddpackage(
    NAME
    SDL3
    GITHUB_REPOSITORY
    libsdl-org/SDL
    GIT_TAG
    5ac37a8ffcf89da390404c1016833d56e2d67ae4
    OPTIONS
    "SDL_STATIC ON"
    "SDL_SHARED OFF"
    "SDL_CCACHE ON"
    "SDL_WAYLAND OFF"
    "SDL_WAYLAND_LIBDECOR OFF"
    "SDL_WAYLAND_LIBDECOR_SHARED OFF"
    "SDL_WAYLAND_QT_TOUCH OFF"
    "SDL_WAYLAND_SHARED OFF"
    "SDL_DISABLE_INSTALL ON"
    "SDL_DISABLE_INSTALL_CPACK ON"
    "SDL_DISABLE_INSTALL_MAN ON"
    "SDL_DISABLE_UNINSTALL ON"
    "SDL_VULKAN OFF"
    "SDL_ASSEMBLY OFF"
    "SDL_TEST OFF"
    "SDL_TESTS OFF"
    "SDL_ROCKCHIP OFF")